### ISSUE TITLE
error on vim 8.2

### ISSUE THREAD

**Issue by zoranbosnjak** [inkarkat/vim-SyntaxRange#14] opened 2022-06-20 10:43 UTC
**Describe the bug**

I have been using vim-SyntaxRange on vim 8.1 without problems. The same configuration reports error on vim 8.2, for example:

```bash
$ vim test.md
Error detected while processing /usr/share/vim/vimrc[25]../usr/share/vim/vim82/syntax/syntax.vim[42]..BufRead Autocommands for "*.md"..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>4_SynSet[25]..script /home/ubuntu/.vim/after/syntax/markdown/SyntaxInclude.vim:
line    1:
E117: Unknown function: SyntaxRange#Include
E117: Unknown function: SyntaxRange#Include
Press ENTER or type command to continue
```

**How to Reproduce**

```bash
mkdir -p ~/.vim/pack/my-plugins/start
mkdir -p ~/.vim/after/syntax/markdown/

vim ~/.vim/after/syntax/markdown/SyntaxInclude.vim
--- (file content)
:call SyntaxRange#Include('```bash', '```', 'bash', 'NonText')
---

cd .vim/pack/my-plugins/start
git clone https://github.com/inkarkat/vim-SyntaxRange

vim test.md
```

**Expected Behavior**

Vim editor should open new file without error.

**Environment**

plugin revision: 3a7fd9f

Working environment: ubuntu 20.04, vim version 8.1.3741
Non-working environment: ubuntu 22.04, vim version 8.2.3995

**Comment by inkarkat** [comment] 2022-06-20 20:46
Looks like a problem with your `'runtimepath'`. I use the plugin with Vim 8.2.4765 myself. Does it only fail when a file is already passed to Vim (then it's an initialization ordering issue), or does `call SyntaxRange#Include(...)` also fail after Vim has started (then the plugin has not been added to the runtimepath at all)?

**Comment by zoranbosnjak** [comment] 2022-06-21 06:39
Once in the editor, the `call SyntaxRange#Include(...)` does not fail. For example:

```bash
rm ~/.vim/after/syntax/markdown/SyntaxInclude.vim
vim test.md
# inside the editor
# :call SyntaxRange#Include('```bash', '```', 'bash', 'NonText')
# no error
```

It looks like a different behaviour between vim versions, regarding the initialization. I am using the original version from ubuntu-22.04. Is there anything I can do to workaround the problem on the current vim version?

**Comment by inkarkat** [comment] 2022-06-21 19:00
That's strange, especially because it's just the autoload script that you're using, and that one will be loaded on-demand, so all that's required is that the plugin's root directory is included in `'runtimepath'`, and that happens really early during Vim startup - usually.

If you want to look deeper into this, you could `:echo &runtimepath` in your `~/.vim/after/syntax/markdown/SyntaxInclude.vim` file, and compare that with the complete `:set runtimepath` after Vim startup. The `:scriptnames` command also is useful to show what (and in which order) got loaded already.

A possible workaround would be to add `:set runtimepath+=~/.vim/pack/my-plugins/start/vim-SyntaxRange` at the top of `~/.vim/after/syntax/markdown/SyntaxInclude.vim`; that should fix the issue, but it's a horribly bad workaround, and the problem could reappear elsewhere, too.

**Comment by zoranbosnjak** [comment] 2022-06-22 12:47
Indeed, the loading order of the scripts looks strange...

```bash
rm ~/.vim/after/syntax/markdown/SyntaxInclude.vim
vim test.md
:scriptnames
```

... gives the following listing:

```  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim82/debian.vim
  3: /usr/share/vim/vim82/syntax/syntax.vim
  4: /usr/share/vim/vim82/syntax/synload.vim
  5: /usr/share/vim/vim82/syntax/syncolor.vim
  6: /usr/share/vim/vim82/colors/lists/default.vim
  7: /usr/share/vim/vim82/filetype.vim
  8: /usr/share/vim/vim82/syntax/markdown.vim
  9: /usr/share/vim/vim82/syntax/html.vim
 10: /usr/share/vim/vim82/syntax/javascript.vim
 11: /usr/share/vim/vim82/syntax/vb.vim
 12: /usr/share/vim/vim82/syntax/css.vim
 13: /usr/share/vim/vim82/defaults.vim
 14: /usr/share/vim/vim82/ftplugin.vim
 15: /usr/share/vim/vim82/indent.vim
 16: /usr/share/vim/vim82/syntax/nosyntax.vim
 17: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 18: /usr/share/vim/vim82/plugin/gzip.vim
 19: /usr/share/vim/vim82/plugin/logiPat.vim
 20: /usr/share/vim/vim82/plugin/manpager.vim
 21: /usr/share/vim/vim82/plugin/matchparen.vim
 22: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 23: /usr/share/vim/vim82/plugin/rrhelper.vim
 24: /usr/share/vim/vim82/plugin/spellfile.vim
 25: /usr/share/vim/vim82/plugin/tarPlugin.vim
 26: /usr/share/vim/vim82/plugin/tohtml.vim
 27: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 28: /usr/share/vim/vim82/plugin/zipPlugin.vim
 29: ~/.vim/pack/my-plugins/start/vim-SyntaxRange/plugin/SyntaxRange.vim
 30: /usr/share/vim/vim82/ftplugin/markdown.vim
 31: /usr/share/vim/vim82/ftplugin/html.vim
 32: /usr/share/vim/vim82/autoload/htmlcomplete.vim
Press ENTER or type command to continue
```

But when the `...after...` is present

```bash
touch ~/.vim/after/syntax/markdown/SyntaxInclude.vim
vim test.md
:scriptnames
```

... it shows that `SyntaxInclude` is loaded at line 13, which is before the `SyntaxRange`.

```
  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim82/debian.vim
  3: /usr/share/vim/vim82/syntax/syntax.vim
  4: /usr/share/vim/vim82/syntax/synload.vim
  5: /usr/share/vim/vim82/syntax/syncolor.vim
  6: /usr/share/vim/vim82/colors/lists/default.vim
  7: /usr/share/vim/vim82/filetype.vim
  8: /usr/share/vim/vim82/syntax/markdown.vim
  9: /usr/share/vim/vim82/syntax/html.vim
 10: /usr/share/vim/vim82/syntax/javascript.vim
 11: /usr/share/vim/vim82/syntax/vb.vim
 12: /usr/share/vim/vim82/syntax/css.vim
 13: ~/.vim/after/syntax/markdown/SyntaxInclude.vim
 14: /usr/share/vim/vim82/defaults.vim
 15: /usr/share/vim/vim82/ftplugin.vim
 16: /usr/share/vim/vim82/indent.vim
 17: /usr/share/vim/vim82/syntax/nosyntax.vim
 18: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 19: /usr/share/vim/vim82/plugin/gzip.vim
 20: /usr/share/vim/vim82/plugin/logiPat.vim
 21: /usr/share/vim/vim82/plugin/manpager.vim
 22: /usr/share/vim/vim82/plugin/matchparen.vim
 23: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 24: /usr/share/vim/vim82/plugin/rrhelper.vim
 25: /usr/share/vim/vim82/plugin/spellfile.vim
 26: /usr/share/vim/vim82/plugin/tarPlugin.vim
 27: /usr/share/vim/vim82/plugin/tohtml.vim
 28: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 29: /usr/share/vim/vim82/plugin/zipPlugin.vim
 30: ~/.vim/pack/my-plugins/start/vim-SyntaxRange/plugin/SyntaxRange.vim
 31: /usr/share/vim/vim82/ftplugin/markdown.vim
 32: /usr/share/vim/vim82/ftplugin/html.vim
 33: /usr/share/vim/vim82/autoload/htmlcomplete.vim
Press ENTER or type command to continue
```

In the case of ubuntu-20.04 (the working configuration), the `...after...` line is loaded near the end of the listing, and comes after the `SyntaxRange`. From this test it looks like the loading order is the problem.

Regarding the suggested workaround, it does not show any error on vim startup, but the range highlighting function does not work automatically either. So, I am getting the same result as not having the `~/.vim/after/syntax/markdown/SyntaxInclude.vim` file.

Could you try it with ubuntu-22.04? An empty virtual server will be just fine to reproduce the problem. For example, I can reproduce it with lxc/lxd container:

```bash
lxc launch ubuntu:22.04 test2
lxc exec test2 bash
sudo su -l ubuntu
...
```

**Comment by inkarkat** [comment] 2022-06-24 18:43
I'm able to reproduce the problem on Ubuntu 22.04 with the distribution's Vim 8.2.3995. However, with a recent Vim 8.2.5155, the problem does not occur. So I guess it's a regression in Vim that has been fixed in the meantime. Too bad that such a version got chosen for the LTS release :-(

You can either update Vim, or work around the problem (e.g. by explicitly `:source`ing the plugin's autoload file:

```
source ~/.vim/pack/my-plugins/start/vim-SyntaxRange/autoload/SyntaxRange.vim
call SyntaxRange#Include('```bash', '```', 'bash', 'NonText')
```

**Closed as completed by inkarkat** 2022-06-24 18:43 UTC
Labels: offtopic

**Comment by zoranbosnjak** [comment] 2022-06-27 11:18
@inkarkat thanks for troubleshooting. But suggested workaround with `:source` directive does not work on Ubuntu 22.04. There is no error at startup, as originally reported by this issue, but the `call SyntaxRange...` seems to be ignored at initialization. Highlightning does not work, unless I manually run `:call SyntaxRange...`. Could you confirm that the workaround actually works with your setup (22.04, original vim version) or were you focused only to the absence of initialization error?

**Comment by inkarkat** [comment] 2022-06-27 14:22
Yes, it's fully working, including Bash highlighting, immediately after Vim is opened with a passed `test.md` file.
