### ISSUE TITLE
Last character is in error color

### ISSUE THREAD

**Issue by antoyo** [inkarkat/vim-SyntaxRange#10] opened 2021-03-03 16:01 UTC
**Describe the bug**

The last character of JSON highlighting is red instead of the normal color like in the following image:

![json_hl](https://user-images.githubusercontent.com/584972/109833852-9caeff00-7c0f-11eb-9f43-eba4d19ff8fb.png)

**How to Reproduce**

1. Create a document with the following content:
```toml
[test]
json = """
{
    "test": 12
}
"""
```
2. Select the JSON and type `:SyntaxInclude json`.

**Expected Behavior**

The last character should be the normal JSON color, instead of red.

**Environment**
 - Plugin version revision _3a7fd9ff50fabafe61df12522ed2f275c8e2f45e_ from the master branch
 - Dependency versions ([ingo-library plugin](https://github.com/inkarkat/vim-ingo-library) revision _8845fbfb4927bdfbda5e1cf50e3226c1c1b47295_)
 - Vim version: `NVIM v0.4.4`
 - OS: ArchLinux
 - Install method: `vim-plug`

**Comment by inkarkat** [comment] 2021-03-03 21:36
This is caused by this `jsonMissingCommaError` syntax definition:

	syn match   jsonMissingCommaError /\("\|\]\|\d\)\zs\_s\+\ze"/

This highlights trailing whitespace (including a line break because of `\_s`), and asserts a following double quote. Now the problem is that your separator is such double quote, and this makes the newline at the inclusion border match; as a newline has no physical presence, the highlighting "moves forward" to the closing brace.

I tried tweaking the syntax inclusion range, but I only found these workarounds for the problem:

* exclude the last line with the `}` from the range
* remove that error highlighting: `syn clear jsonMissingCommaError` / all error highlighting: `:let g:vim_json_warnings = 0`
* use a different character sequence than `"""` (if the syntax allowed that)

**Comment by antoyo** [comment] 2021-03-04 14:23
Would it be possible to exclude the newline with something like:
```
call SyntaxRange#Include('"""', '\n"""', 'json', 'NonText')
```
?

**Comment by inkarkat** [comment] 2021-03-04 20:35
I tried something along that line as well, but did not succeed, even though the plugin uses `keepend`, and that should restrict inner matches from extending.

**Comment by antoyo** [comment] 2021-03-05 18:44
Ok, I'm okay with the workarounds.
If you think that's an issue in `vim` itself and thus won't be able to fix it in the plugin, you can close this issue.

**Comment by inkarkat** [comment] 2021-03-05 19:06
Well, not so much an issue with Vim itself; it's more that defining a good interface that allows for seamless syntax extension is hard, and not in the primary focus of a syntax script author. It can be done (e.g. JavaScript inside HTML, or Doxygen comments inside C/C++), but many syntaxes don't account for that.

My plugin tries to offer a quick way for users to retrofit such integrations, but the nature of that is that it's rarely perfect.

**Closed as completed by inkarkat** 2021-03-05 19:06 UTC
